---
title: emerge -u system (2)
date: 2004-02-09T00:00:00.000Z
lastmod: 2004-03-16T02:53:40.000Z
draft: false
tags:
  - Gentoo
---

昨日から[Gentooのアップデート](/posts/20040208/p04)をしていたのだけど、終わってみたらこんなエラーがでるようになった。

```
$ emerge -up system

These are the packages that I would merge, in order:

Calculating system dependencies \Traceback (most recent call last):
  File "/usr/bin/emerge", line 2513, in ?
    if not mydepgraph.xcreate(myaction):
  File "/usr/bin/emerge", line 1105, in xcreate
    myeb=portage.portdb.xmatch("bestmatch-visible",mydep)
  File "/usr/lib/portage/pym/portage.py", line 4673, in xmatch
    myval=best(self.xmatch("match-visible",None,mydep,mykey))
  File "/usr/lib/portage/pym/portage.py", line 4684, in xmatch
    myval=match_from_list(mydep,self.xmatch("list-visible",None,mydep,mykey))
  File "/usr/lib/portage/pym/portage.py", line 4670, in xmatch
    myval=self.gvisible(self.visible(self.cp_list(mykey)))
  File "/usr/lib/portage/pym/portage.py", line 4765, in gvisible
    myaux=db["/"]["porttree"].dbapi.aux_get(mycpv, ["KEYWORDS"])
  File "/usr/lib/portage/pym/portage.py", line 4509, in aux_get
    auxdb_is_valid = self.auxdb[cat].has_key(pkg) and \
  File "/usr/lib/portage/pym/portage_db_template.py", line 15, in __getitem__
    return self.get_values(key)
  File "/usr/lib/portage/pym/portage_db_flat.py", line 58, in get_values
    raise ValueError, "Key count mismatch"
ValueError: Key count mismatch
```

まいったなぁ・・・。
